# Webbplatsens grundinställningar
title: My Orchids
email: info@myorchids.se
description: >-
  My Orchids is your ultimate app for caring for and keeping track of your orchids. 
  Perfect for both beginners and seasoned orchid enthusiasts.

# URL-inställningar för GitHub Pages
# Lämna url tom eller sätt till din domän. När du kör lokalt skriver Jekyll över detta automatiskt.
url: "https://henrik730507.github.io"
baseurl: "/myorchids-website"

# Bygginställningar
markdown: kramdown

# Exkludera filer och mappar från att byggas (ökar hastigheten)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .jekyll-cache
  - .jekyll-metadata
  - README.md
